
server:
  port: 8081 #配置服务器端口，默认为8080
  session:
    timeout: 1000000 #用户回话session过期时间，以秒为单位
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: eureka-ording
  thymeleaf:
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false #开发时关闭缓存,不然没法看到实时页面
      prefix: classpath:/templates
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mydata:
  db-url: jdbc:mysql://localhost:3306/ordering?characterEncoding=utf8
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  mapper-path: classpath*:/XML/*.xml
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://horcrux:hor66@127.0.0.1:8651/eureka/
test: false;