server:
  port: 8080 #配置服务器端口，默认为8080
  session:
    timeout: 1000000 #用户回话session过期时间，以秒为单位
  tomcat:
    uri-encoding: UTF-8

spring:
  thymeleaf:
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false #开发时关闭缓存,不然没法看到实时页面
      prefix: classpath:/templates
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name:


data:
  url: jdbc:mysql://localhost:3306/ordering?characterEncoding=utf8 #?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: root
  driverClassName: com.mysql.jdbc.Driver